### ISSUE TITLE
Make Node-compatible and package for NPM

### ISSUE THREAD

**Issue by strogonoff** [interscript/interscript-js#4]
This may or may not be complicated.

**Comment by strogonoff** [comment]
I published Interscript.js on NPM and added examples in README, but properly making it a module will require more effort. Currently it just exposes the API as a global variable, which is contrary to best practices.

I’ve looked at Asciidoctor.js and it has a lot of code dedicated to properly exposing JS after it’s generated from Opal. Also notably they don’t version generated JS—it is created from Ruby at build time (similar to how we version only TS, and generate JS at build time).

(cc @ronaldtse)

**Comment by ronaldtse** [comment]
> I’ve looked at Asciidoctor.js and it has a lot of code dedicated to properly exposing JS after it’s generated from Opal. 

Then we should do that too. Will file an issue.

> Also notably they don’t version generated JS—it is created from Ruby at build time (similar to how we version only TS, and generate JS at build time).

We'd like to do that as we have done for others, e.g. the mn2pdf JAR in the Ruby gem of the same name, it's just a matter of who will setup the build flow. I will file this.

**Comment by strogonoff** [comment]
> Will file an issue.

Thank you! Have to be honest, I’m not ready to dive into this right now—seems like a whole new context. It boils down to not using globals and using exports instead, and the tricky parts as far as I can see are:

* Making sure globals are not used but Opal code still works.
* Making any customizations on top of Opal-generated JS fully automated, there should be no manual involvement. E.g., if Opal-generated JS needs to be adapted to not use globals, there should be a script that does that during build. (We can version a layer around Opal, but we should not version Opal-generated code itself, it should be a build artifact.)

**Comment by webdev778** [comment]
Done.
