### ISSUE TITLE
Demo in index.html does not work

### ISSUE THREAD

**Issue by strogonoff** [interscript/interscript-js#6]
I am seeing empty selector of conversion systems. Same behavior regardless of whether I open index.html directly or serve it locally.

<img width="1296" alt="Screenshot 2020-09-01 at 1 10 19 PM" src="https://user-images.githubusercontent.com/292959/91794094-1a8c5080-ec55-11ea-8eec-3c246ea3f671.png">

**Comment by ronaldtse** [comment]
Fixed in 6432a39
