### ISSUE TITLE
Clarify that the library is Opal-converted?

### ISSUE THREAD

**Issue by strogonoff** [interscript/interscript-js#7]
- Those that don’t realize it’s Opal-generated will be appalled at the quality and weight of JS
- To others it will be obvious it’s Opal-generated, but why not be upfront to save the hassle?
- Some environments (such as browser client-side in most cases) preclude use of Opal-converted JS because large size is unfriendly to visitors.

Asciidoctor.js makes it fairly obvious it’s generated using Opal, for example.

**Comment by ronaldtse** [comment]
We haven't had time to update the description. Can you help?

**Comment by ronaldtse** [comment]
It's no longer opal generated.
